let map = new Map();
 map.set(101,'Parâmetros de login inválidos');
 map.set(102,'Há um problema com os parâmetros usados ​​para construir essa consulta. Isso pode ser um nome de campo inválido ou um tipo de campo inválido para uma restrição específica');
 map.set(103,'Nome de classe ausente ou inválido. Os Classnames distinguem maiúsculas de minúsculas. Eles devem começar com uma letra, e a-zA-Z0-9_ são os únicos caracteres válidos.');
 map.set(104,'Um id de objeto não especificado');
 map.set(105,'Um nome de campo inválido. As teclas são sensíveis a maiúsculas e minúsculas');
 map.set(106,'Um ponteiro malformado foi usado.');
 map.set(107,'JSON mal formado foi recebido upstream');
 map.set(108,'O recurso que você tentou acessar está disponível apenas internamente para fins de teste');
 map.set(109,'Há um problema com os parâmetros usados ​​para construir essa consulta. Isso pode ser um nome de campo inválido ou um tipo de campo inválido para uma restrição específica');
 map.set(116,'O objeto é muito grande. Objetos de análise têm um tamanho máximo de 128 kilobytes/Você atingiu o limite de 100 parâmetros de configuração');
 map.set(117,'Um valor inválido foi definido para o limite.');
 map.set(118,'Um valor inválido foi definido para ignorar.');
 map.set(119,'A operação não é permitida para clientes devido a permissões de nível de classe.');
 map.set(120,' O resultado não foi encontrado no cache.');
 map.set(121,'Uma chave inválida foi usada em um JSONObject aninhado.');
 map.set(123,'Uma ACL inválida foi fornecida.');
 map.set(125,'O endereço de e-mail era inválido.');
 map.set(137,'Campo duplicado.');
 map.set(139,'Valor de campo reservado/ Regra inválida');
 map.set(140,'Você atingiu a cota no número de classes em seu aplicativo.');
 map.set(141,'Execução do script na nuvem falhou/Script não encontrado.');
 map.set(256,'O nome da aplicação é inválido');
 map.set(902,'A solicitação está faltando uma chave de API.');
 map.set(903,'A solicitação está usando uma chave de API inválida');
export default map;
